package com.hf.study.socket.dao.entity;

import java.io.Serializable;
import java.sql.*;
import javax.persistence.*;
import lombok.Data;
import lombok.ToString;

/**
 * 用户表
 * auto-generated by jpa-entity-generator
 */
@Data
@ToString
@Entity(name = "com.hf.study.socket.dao.entity.ImUser")
@Table(name = "im_user")
public class ImUser implements Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"")
  private Long id;
  /**
   * 用户名称
   */
  @Column(name = "\"username\"")
  private String username;
  /**
   * 用户密码
   */
  @Column(name = "\"password\"")
  private String password;
  /**
   * 创建时间
   */
  @Column(name = "\"create_time\"")
  private Timestamp createTime;
  /**
   * 创建时间
   */
  @Column(name = "\"update_time\"")
  private Timestamp updateTime;
}